scan_filter_chain:
- name: Angular1
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle:
    upper_angle:

- name: Angular2
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle:
    upper_angle:

- name: Angular3
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle:
    upper_angle:

- name: Angular4
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle:
    upper_angle: